### PR TITLE
Content, Buttons alignment, Typeface

### PR DESCRIPTION
**Pull request by alirezaafkar**
Since my language is right to left, I've added content and buttons alignment.

CustomDialog.Builder builder = new CustomDialog.Builder(Context context, String title, String positiveText);
builder.rightToLeft(true);
//or
builder.mTitleAlignment (Alignment.RIGHT);
builder.mContentAlignment(Alignment.RIGHT);
builder.mButtonsAlignment(Alignment.LEFT);

//I've added typeface for builder too.

Typeface tf = Typeface.createFromAsset(this.getResources()
                    .getAssets(), "Custom.ttf");
builder.typeFace(tf);

### CODE REVIEW

**Comment by lewisjdeane** [comment]
Okay looks good to me, although I can't merge it as there is conflicts, I think you may have to update to the latest version and merge yours from there before I can.

**Comment by lewisjdeane** [comment]
Actually don't worry, i've manually merged them through git bash.

**Comment by alirezaafkar** [comment]
Thanks !
And please make this change for : dialog_custom_stacked_buttons

android:layout_width="wrap_content"
to 
android:layout_width="match_parent"

**Comment by lewisjdeane** [comment]
Yes I will be sure to do that, sorry for the delay in pulling this request.

**Pull request closed without merging**
